# Generated by Django 3.2.4 on 2022-03-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0006_following_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
